web:
  build: .
  dockerfile: Docker.file
  links:
   - db:postgres
   - search:elasticsearch
   - redis
  ports:
   - "8000:8000"
  volumes:
   - .:/code
  environment:
   - DATABASE_NAME=postgres
   - DATABASE_PASSWORD=
db:
  image: postgres
redis:
  image: redis
search:
  image: elasticsearch
